# Generated by Django 5.2.3 on 2025-06-18 18:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Formato: YYYY-YYYY, ej: 2023-2024",
                        max_length=100,
                        unique=True,
                        verbose_name="Año Académico (ej: 2023-2024)",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Fecha de Inicio del Año Académico"),
                ),
                (
                    "end_date",
                    models.DateField(verbose_name="Fecha de Fin del Año Académico"),
                ),
            ],
            options={
                "verbose_name": "Año Académico",
                "verbose_name_plural": "Años Académicos",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="GradingScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Scale Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Grading Scale",
                "verbose_name_plural": "Grading Scales",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "duration_years",
                    models.IntegerField(verbose_name="Duration (Years)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("TEACHER", "Teacher"),
                            ("STUDENT", "Student"),
                            ("PARENT", "Parent"),
                            ("DIRECTOR", "Director"),
                        ],
                        default="STUDENT",
                        max_length=10,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="GradeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Grado/Año de Estudio"
                    ),
                ),
                (
                    "order_in_level",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Para ordenar los grados/años dentro de un nivel educativo (ej: 1 para 1er año, 2 para 2do año).",
                        verbose_name="Orden dentro del Nivel",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_levels",
                        to="core.level",
                        verbose_name="Nivel Educativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grado/Año de Estudio",
                "verbose_name_plural": "Grados/Años de Estudio",
                "ordering": ["level__name", "order_in_level", "name"],
                "unique_together": {("level", "name")},
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        verbose_name="Nombre de la Sección (ej: A, B, Única)",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="year_sections",
                        to="core.academicyear",
                        verbose_name="Año Académico (Ciclo Escolar)",
                    ),
                ),
                (
                    "grade_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.gradelevel",
                        verbose_name="Grado/Año de Estudio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
                "ordering": [
                    "academic_year__name",
                    "grade_level__level__name",
                    "grade_level__order_in_level",
                    "name",
                ],
                "unique_together": {("name", "grade_level", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="AcademicPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        verbose_name="Nombre del Lapso (ej: 1er Lapso, ASP)",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Fecha de Inicio del Lapso"),
                ),
                ("end_date", models.DateField(verbose_name="Fecha de Fin del Lapso")),
                (
                    "grading_open_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha desde la cual se pueden cargar notas para este lapso.",
                        null=True,
                        verbose_name="Inicio de Carga de Notas del Lapso",
                    ),
                ),
                (
                    "grading_close_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha hasta la cual se pueden cargar notas para este lapso.",
                        null=True,
                        verbose_name="Cierre de Carga de Notas del Lapso",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="core.academicyear",
                        verbose_name="Año Académico (YYYY-YYYY)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lapso Académico",
                "verbose_name_plural": "Lapsos Académicos",
                "ordering": ["academic_year__start_date", "start_date", "name"],
                "unique_together": {("academic_year", "name")},
            },
        ),
        migrations.CreateModel(
            name="GradeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_value",
                    models.CharField(
                        max_length=20,
                        verbose_name="Display Value (e.g., A, B, 20, Pass)",
                    ),
                ),
                (
                    "numeric_equivalent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Numeric Equivalent",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Order for display in dropdowns/lists",
                        verbose_name="Order",
                    ),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="core.gradingscale",
                        verbose_name="Scale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Value",
                "verbose_name_plural": "Grade Values",
                "ordering": ["scale", "order", "numeric_equivalent"],
                "unique_together": {("scale", "display_value")},
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Inscripción"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="core.section",
                        verbose_name="Sección Inscrita",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción de Estudiante",
                "verbose_name_plural": "Inscripciones de Estudiantes",
                "ordering": [
                    "section__academic_year__name",
                    "section__grade_level__order_in_level",
                    "section__name",
                    "student__last_name",
                    "student__first_name",
                ],
                "unique_together": {("student", "section")},
            },
        ),
        migrations.CreateModel(
            name="SubjectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hourly_load",
                    models.PositiveIntegerField(
                        help_text="Número de horas de esta asignatura a la semana para este grado.",
                        verbose_name="Carga Horaria Semanal (horas)",
                    ),
                ),
                (
                    "grade_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_assignments",
                        to="core.gradelevel",
                        verbose_name="Grado/Año de Estudio",
                    ),
                ),
                (
                    "grading_scale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subject_assignments_using_this_scale",
                        to="core.gradingscale",
                        verbose_name="Escala de Calificación (Opcional)",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_level_assignments",
                        to="core.subject",
                        verbose_name="Asignatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Materia a Grado",
                "verbose_name_plural": "Asignaciones de Materias a Grados",
                "ordering": [
                    "grade_level__level__name",
                    "grade_level__order_in_level",
                    "subject__name",
                ],
                "unique_together": {("subject", "grade_level")},
            },
        ),
    ]
