# Generated by Django 5.2.3 on 2025-06-18 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="core.academicyear",
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_enrollments",
                to="core.section",
            ),
        ),
        migrations.AlterField(
            model_name="subjectassignment",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_assignments",
                to="core.academicyear",
            ),
        ),
        migrations.AlterField(
            model_name="subjectassignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_to_academic_years",
                to="core.subject",
            ),
        ),
    ]
