# Generated by Django 5.2.3 on 2025-06-20 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreEnrollmentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto_alumno",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="preenrollment_photos/",
                        verbose_name="Foto del Alumno",
                    ),
                ),
                (
                    "nombres_alumno",
                    models.CharField(max_length=100, verbose_name="Nombres del Alumno"),
                ),
                (
                    "apellidos_alumno",
                    models.CharField(
                        max_length=100, verbose_name="Apellidos del Alumno"
                    ),
                ),
                (
                    "cedula_alumno",
                    models.CharField(
                        help_text="Formato: V12345678 o E12345678",
                        max_length=20,
                        unique=True,
                        verbose_name="Número de Cédula del Alumno",
                    ),
                ),
                (
                    "pais_nacimiento_alumno",
                    models.CharField(
                        max_length=100, verbose_name="País de Nacimiento del Alumno"
                    ),
                ),
                (
                    "estado_nacimiento_alumno",
                    models.CharField(
                        max_length=100,
                        verbose_name="Estado/Provincia de Nacimiento del Alumno",
                    ),
                ),
                (
                    "municipio_nacimiento_alumno",
                    models.CharField(
                        max_length=100,
                        verbose_name="Municipio/Ciudad de Nacimiento del Alumno",
                    ),
                ),
                (
                    "lugar_residencia_actual_alumno",
                    models.TextField(
                        verbose_name="Dirección de Residencia Actual del Alumno"
                    ),
                ),
                (
                    "edad_alumno",
                    models.PositiveIntegerField(
                        verbose_name="Edad del Alumno (años cumplidos)"
                    ),
                ),
                (
                    "correo_electronico_alumno",
                    models.EmailField(
                        max_length=254, verbose_name="Correo Electrónico del Alumno"
                    ),
                ),
                (
                    "grado_aspirado_nombre_temporal",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nombre Temporal del Grado Aspirado",
                    ),
                ),
                (
                    "nombres_madre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Nombres Completos (Madre)",
                    ),
                ),
                (
                    "apellidos_madre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Apellidos Completos (Madre)",
                    ),
                ),
                (
                    "cedula_madre",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Cédula de Identidad (Madre)",
                    ),
                ),
                (
                    "pais_nacimiento_madre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="País de Nacimiento (Madre)",
                    ),
                ),
                (
                    "estado_nacimiento_madre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Estado de Nacimiento (Madre)",
                    ),
                ),
                (
                    "municipio_nacimiento_madre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Municipio de Nacimiento (Madre)",
                    ),
                ),
                (
                    "lugar_residencia_actual_madre",
                    models.TextField(
                        blank=True, verbose_name="Residencia Actual (Madre)"
                    ),
                ),
                (
                    "edad_madre",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Edad (Madre)"
                    ),
                ),
                (
                    "correo_electronico_madre",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Correo Electrónico (Madre)",
                    ),
                ),
                (
                    "rif_madre",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="RIF (Madre)"
                    ),
                ),
                (
                    "profesion_madre",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Profesión (Madre)"
                    ),
                ),
                (
                    "lugar_trabajo_madre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Lugar de Trabajo (Madre)",
                    ),
                ),
                (
                    "telefono_habitacion_madre",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Teléfono Habitación (Madre)",
                    ),
                ),
                (
                    "telefono_movil_madre",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono Móvil (Madre)"
                    ),
                ),
                (
                    "madre_fallecida",
                    models.BooleanField(default=False, verbose_name="Madre Fallecida"),
                ),
                (
                    "nombres_padre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Nombres Completos (Padre)",
                    ),
                ),
                (
                    "apellidos_padre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Apellidos Completos (Padre)",
                    ),
                ),
                (
                    "cedula_padre",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Cédula de Identidad (Padre)",
                    ),
                ),
                (
                    "pais_nacimiento_padre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="País de Nacimiento (Padre)",
                    ),
                ),
                (
                    "estado_nacimiento_padre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Estado de Nacimiento (Padre)",
                    ),
                ),
                (
                    "municipio_nacimiento_padre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Municipio de Nacimiento (Padre)",
                    ),
                ),
                (
                    "lugar_residencia_actual_padre",
                    models.TextField(
                        blank=True, verbose_name="Residencia Actual (Padre)"
                    ),
                ),
                (
                    "edad_padre",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Edad (Padre)"
                    ),
                ),
                (
                    "correo_electronico_padre",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Correo Electrónico (Padre)",
                    ),
                ),
                (
                    "rif_padre",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="RIF (Padre)"
                    ),
                ),
                (
                    "profesion_padre",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Profesión (Padre)"
                    ),
                ),
                (
                    "lugar_trabajo_padre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Lugar de Trabajo (Padre)",
                    ),
                ),
                (
                    "telefono_habitacion_padre",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Teléfono Habitación (Padre)",
                    ),
                ),
                (
                    "telefono_movil_padre",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono Móvil (Padre)"
                    ),
                ),
                (
                    "padre_fallecido",
                    models.BooleanField(default=False, verbose_name="Padre Fallecido"),
                ),
                (
                    "peso_alumno_kg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Peso del Alumno (kg)"
                    ),
                ),
                (
                    "altura_alumno_cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Altura del Alumno (cm)"
                    ),
                ),
                (
                    "talla_pantalon_alumno",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Talla de Pantalón"
                    ),
                ),
                (
                    "talla_camisa_alumno",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Talla de Camisa"
                    ),
                ),
                (
                    "talla_zapatos_alumno",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Talla de Zapatos"
                    ),
                ),
                (
                    "vacunas_recibidas_json",
                    models.JSONField(
                        blank=True,
                        help_text="Almacena la selección de vacunas del formulario.",
                        null=True,
                        verbose_name="Vacunas Recibidas (JSON)",
                    ),
                ),
                (
                    "otras_vacunas_especificar",
                    models.TextField(
                        blank=True, verbose_name="Otras Vacunas Especificadas"
                    ),
                ),
                (
                    "condiciones_medicas_relevantes",
                    models.TextField(
                        blank=True, verbose_name="Condiciones Médicas Relevantes"
                    ),
                ),
                (
                    "alergias_conocidas",
                    models.TextField(blank=True, verbose_name="Alergias Conocidas"),
                ),
                (
                    "medicamentos_regulares",
                    models.TextField(
                        blank=True, verbose_name="Medicamentos que Toma Regularmente"
                    ),
                ),
                (
                    "seguro_medico",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Seguro Médico (Compañía y Póliza)",
                    ),
                ),
                (
                    "vehiculos_json",
                    models.JSONField(
                        blank=True,
                        help_text="Ej: [{'tipo':'Carro', 'marca':'Toyota', 'modelo':'Corolla', 'placa':'XYZ-123', 'color':'Rojo'}, ...]",
                        null=True,
                        verbose_name="Información de Vehículos (JSON)",
                    ),
                ),
                (
                    "quien_es_representante_legal_opcion",
                    models.CharField(
                        choices=[
                            ("madre", "Madre"),
                            ("padre", "Padre"),
                            ("otro", "Otro"),
                        ],
                        max_length=30,
                        verbose_name="Opción Representante Legal",
                    ),
                ),
                (
                    "nombres_rl_otro",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Nombres Completos (Rep. Legal Otro)",
                    ),
                ),
                (
                    "apellidos_rl_otro",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Apellidos Completos (Rep. Legal Otro)",
                    ),
                ),
                (
                    "cedula_rl_otro",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Cédula (Rep. Legal Otro)",
                    ),
                ),
                (
                    "pais_nacimiento_rl_otro",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="País Nacimiento (Rep. Legal Otro)",
                    ),
                ),
                (
                    "estado_nacimiento_rl_otro",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Estado Nacimiento (Rep. Legal Otro)",
                    ),
                ),
                (
                    "municipio_nacimiento_rl_otro",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Municipio Nacimiento (Rep. Legal Otro)",
                    ),
                ),
                (
                    "lugar_residencia_actual_rl_otro",
                    models.TextField(
                        blank=True, verbose_name="Residencia Actual (Rep. Legal Otro)"
                    ),
                ),
                (
                    "edad_rl_otro",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Edad (Rep. Legal Otro)"
                    ),
                ),
                (
                    "correo_electronico_rl_otro",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Correo (Rep. Legal Otro)",
                    ),
                ),
                (
                    "telefono_rl_otro",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Teléfono (Rep. Legal Otro)",
                    ),
                ),
                (
                    "parentesco_rl_otro",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Parentesco con el Alumno (Rep. Legal Otro)",
                    ),
                ),
                (
                    "quien_es_responsable_pago_opcion",
                    models.CharField(
                        choices=[
                            ("madre", "Madre"),
                            ("padre", "Padre"),
                            (
                                "representante_legal_seleccionado",
                                "Mismo Rep. Legal (si es Otro)",
                            ),
                            ("otra_persona_pago", "Otra Persona"),
                        ],
                        max_length=50,
                        verbose_name="Opción Responsable Pago",
                    ),
                ),
                (
                    "nombres_rp_otro",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Nombres Completos (Resp. Pago Otro)",
                    ),
                ),
                (
                    "apellidos_rp_otro",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Apellidos Completos (Resp. Pago Otro)",
                    ),
                ),
                (
                    "cedula_rp_otro",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Cédula (Resp. Pago Otro)",
                    ),
                ),
                (
                    "rif_rp_otro",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="RIF (Resp. Pago Otro)"
                    ),
                ),
                (
                    "pais_nacimiento_rp_otro",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="País Nacimiento (Resp. Pago Otro)",
                    ),
                ),
                (
                    "estado_nacimiento_rp_otro",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Estado Nacimiento (Resp. Pago Otro)",
                    ),
                ),
                (
                    "municipio_nacimiento_rp_otro",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Municipio Nacimiento (Resp. Pago Otro)",
                    ),
                ),
                (
                    "lugar_residencia_actual_rp_otro",
                    models.TextField(
                        blank=True, verbose_name="Residencia (Resp. Pago Otro)"
                    ),
                ),
                (
                    "edad_rp_otro",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Edad (Resp. Pago Otro)"
                    ),
                ),
                (
                    "correo_electronico_rp_otro",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Correo (Resp. Pago Otro)",
                    ),
                ),
                (
                    "telefono_rp_otro",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Teléfono (Resp. Pago Otro)",
                    ),
                ),
                (
                    "parentesco_rp_otro",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Parentesco con el Alumno (Resp. Pago Otro)",
                    ),
                ),
                (
                    "fecha_preinscripcion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Preinscripción"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "estado_preinscripcion",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Revisión"),
                            ("EN_REVISION", "En Revisión Administrativa"),
                            ("APROBADO", "Aprobado para Inscripción"),
                            ("RECHAZADO", "Rechazado"),
                            ("INSCRITO", "Inscrito Formalmente"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado de la Preinscripción",
                    ),
                ),
                (
                    "notas_administrativas",
                    models.TextField(
                        blank=True, verbose_name="Notas Administrativas Internas"
                    ),
                ),
                (
                    "grado_aspirado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.gradelevel",
                        verbose_name="Grado/Año al que Aspira",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planilla de Preinscripción",
                "verbose_name_plural": "Planillas de Preinscripción",
                "ordering": [
                    "-fecha_preinscripcion",
                    "apellidos_alumno",
                    "nombres_alumno",
                ],
            },
        ),
    ]
