# Generated by Django 5.0 on 2024-05-03 10:00

from django.db import migrations
from django.contrib.auth.hashers import make_password # Import make_password

def create_users(apps, schema_editor):
    User = apps.get_model('core', 'User')

    # Create admin user
    # User.objects.create_superuser('admin', 'admin@example.com', 'admin', role='ADMIN')
    # Create_superuser doesn't allow setting role directly.
    # is_staff and is_superuser are True by default with create_superuser
    admin_user = User.objects.create_user(
        username='admin',
        email='admin@example.com',
        password='admin',  # Set a plain password
        role='ADMIN',
        is_staff=True,
        is_superuser=True
    )
    # Hash the password for the admin user (if not handled by create_user)
    # admin_user.password = make_password('admin') # create_user usually handles this
    # admin_user.save()


    # Create professor user
    professor_user = User.objects.create_user(
        username='profesor',
        email='profesor@example.com',
        password='password', # Set a plain password
        role='TEACHER',
        is_staff=True
    )
    # Hash the password for the professor user (if not handled by create_user)
    # professor_user.password = make_password('password') # create_user usually handles this
    # professor_user.save()

def remove_users(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User.objects.filter(username='admin').delete()
    User.objects.filter(username='profesor').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_preenrollmentprofile'), # Adjust dependency if necessary
    ]

    operations = [
        migrations.RunPython(create_users, reverse_code=remove_users),
    ]
