# Generated by Django 5.2.3 on 2025-06-18 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_section_academic_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradingScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Scale Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Grading Scale",
                "verbose_name_plural": "Grading Scales",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="studentenrollment",
            options={
                "verbose_name": "Student Enrollment",
                "verbose_name_plural": "Student Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="subjectassignment",
            options={
                "verbose_name": "Subject Assignment",
                "verbose_name_plural": "Subject Assignments",
            },
        ),
        migrations.AlterField(
            model_name="academicperiod",
            name="end_date",
            field=models.DateField(verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="academicperiod",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="academicperiod",
            name="start_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.level",
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="level",
            name="duration_years",
            field=models.IntegerField(verbose_name="Duration (Years)"),
        ),
        migrations.AlterField(
            model_name="level",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="section",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="core.academicyear",
                verbose_name="Academic Year",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="academic_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.academicperiod",
                verbose_name="Academic Period",
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="enrollment_date",
            field=models.DateField(auto_now_add=True, verbose_name="Enrollment Date"),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_enrollments",
                to="core.section",
                verbose_name="Section",
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "STUDENT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="subjectassignment",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_assignments",
                to="core.academicyear",
                verbose_name="Academic Year",
            ),
        ),
        migrations.AlterField(
            model_name="subjectassignment",
            name="hourly_load",
            field=models.IntegerField(verbose_name="Hourly Load"),
        ),
        migrations.AlterField(
            model_name="subjectassignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_to_academic_years",
                to="core.subject",
                verbose_name="Subject",
            ),
        ),
        migrations.AddField(
            model_name="subjectassignment",
            name="grading_scale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subject_assignments",
                to="core.gradingscale",
                verbose_name="Grading Scale (Optional)",
            ),
        ),
        migrations.CreateModel(
            name="GradeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_value",
                    models.CharField(
                        max_length=20,
                        verbose_name="Display Value (e.g., A, B, 20, Pass)",
                    ),
                ),
                (
                    "numeric_equivalent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Numeric Equivalent",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Order for display in dropdowns/lists",
                        verbose_name="Order",
                    ),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="core.gradingscale",
                        verbose_name="Scale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Value",
                "verbose_name_plural": "Grade Values",
                "ordering": ["scale", "order", "numeric_equivalent"],
                "unique_together": {("scale", "display_value")},
            },
        ),
    ]
