# Generated by Django 5.2.3 on 2025-06-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_gradingscale_alter_studentenrollment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicperiod",
            name="grading_close_date",
            field=models.DateField(
                blank=True,
                help_text="Date after which teachers can no longer input/modify grades for this period (unless admin).",
                null=True,
                verbose_name="Grade Input Close Date",
            ),
        ),
        migrations.AddField(
            model_name="academicperiod",
            name="grading_open_date",
            field=models.DateField(
                blank=True,
                help_text="Date when teachers can start inputting/modifying grades for this period.",
                null=True,
                verbose_name="Grade Input Open Date",
            ),
        ),
    ]
