# Generated by Django 5.2.3 on 2025-06-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_create_default_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="level",
            name="duration_years",
        ),
        migrations.AlterField(
            model_name="level",
            name="name",
            field=models.CharField(
                choices=[
                    ("inicial", "Educación inicial"),
                    ("primaria", "Educación primaria"),
                    ("media_general", "Educación media general"),
                    ("asp", "ASP"),
                    ("extracurricular", "Extracurriculares"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Name",
            ),
        ),
    ]
