# Generated by Django 5.2.3 on 2025-06-18 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_academicperiod_grading_close_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicperiod",
            options={
                "ordering": ["academic_year__start_date", "start_date", "name"],
                "verbose_name": "Lapso Académico",
                "verbose_name_plural": "Lapsos Académicos",
            },
        ),
        migrations.AlterModelOptions(
            name="academicyear",
            options={
                "ordering": ["-start_date", "name"],
                "verbose_name": "Año Académico",
                "verbose_name_plural": "Años Académicos",
            },
        ),
        migrations.AlterModelOptions(
            name="section",
            options={
                "ordering": [
                    "academic_year__name",
                    "grade_level__level__name",
                    "grade_level__order_in_level",
                    "name",
                ],
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
            },
        ),
        migrations.AlterModelOptions(
            name="studentenrollment",
            options={
                "ordering": [
                    "section__academic_year__name",
                    "section__grade_level__order_in_level",
                    "section__name",
                    "student__last_name",
                    "student__first_name",
                ],
                "verbose_name": "Inscripción de Estudiante",
                "verbose_name_plural": "Inscripciones de Estudiantes",
            },
        ),
        migrations.AlterModelOptions(
            name="subjectassignment",
            options={
                "ordering": [
                    "grade_level__level__name",
                    "grade_level__order_in_level",
                    "subject__name",
                ],
                "verbose_name": "Asignación de Materia a Grado",
                "verbose_name_plural": "Asignaciones de Materias a Grados",
            },
        ),
        migrations.RemoveField(
            model_name="academicyear",
            name="level",
        ),
        migrations.AlterUniqueTogether(
            name="studentenrollment",
            unique_together={("student", "section")},
        ),
        migrations.AddField(
            model_name="academicperiod",
            name="academic_year",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="core.academicyear",
                verbose_name="Año Académico (YYYY-YYYY)",
            ),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="end_date",
            field=models.DateField(
                null=True, verbose_name="Fecha de Fin del Año Académico"
            ),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="start_date",
            field=models.DateField(
                null=True, verbose_name="Fecha de Inicio del Año Académico"
            ),
        ),
        migrations.AlterField(
            model_name="academicperiod",
            name="end_date",
            field=models.DateField(verbose_name="Fecha de Fin del Lapso"),
        ),
        migrations.AlterField(
            model_name="academicperiod",
            name="grading_close_date",
            field=models.DateField(
                blank=True,
                help_text="Fecha hasta la cual se pueden cargar notas para este lapso.",
                null=True,
                verbose_name="Cierre de Carga de Notas del Lapso",
            ),
        ),
        migrations.AlterField(
            model_name="academicperiod",
            name="grading_open_date",
            field=models.DateField(
                blank=True,
                help_text="Fecha desde la cual se pueden cargar notas para este lapso.",
                null=True,
                verbose_name="Inicio de Carga de Notas del Lapso",
            ),
        ),
        migrations.AlterField(
            model_name="academicperiod",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Nombre del Lapso (ej: 1er Lapso, ASP)"
            ),
        ),
        migrations.AlterField(
            model_name="academicperiod",
            name="start_date",
            field=models.DateField(verbose_name="Fecha de Inicio del Lapso"),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="name",
            field=models.CharField(
                help_text="Formato: YYYY-YYYY, ej: 2023-2024",
                max_length=100,
                unique=True,
                verbose_name="Año Académico (ej: 2023-2024)",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="year_sections",
                to="core.academicyear",
                verbose_name="Año Académico (Ciclo Escolar)",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Nombre de la Sección (ej: A, B, Única)"
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="enrollment_date",
            field=models.DateField(
                auto_now_add=True, verbose_name="Fecha de Inscripción"
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="core.section",
                verbose_name="Sección Inscrita",
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "STUDENT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Estudiante",
            ),
        ),
        migrations.AlterField(
            model_name="subjectassignment",
            name="grading_scale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subject_assignments_using_this_scale",
                to="core.gradingscale",
                verbose_name="Escala de Calificación (Opcional)",
            ),
        ),
        migrations.AlterField(
            model_name="subjectassignment",
            name="hourly_load",
            field=models.PositiveIntegerField(
                help_text="Número de horas de esta asignatura a la semana para este grado.",
                verbose_name="Carga Horaria Semanal (horas)",
            ),
        ),
        migrations.AlterField(
            model_name="subjectassignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_level_assignments",
                to="core.subject",
                verbose_name="Asignatura",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicperiod",
            unique_together={("academic_year", "name")},
        ),
        migrations.CreateModel(
            name="GradeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Grado/Año de Estudio"
                    ),
                ),
                (
                    "order_in_level",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Para ordenar los grados/años dentro de un nivel educativo (ej: 1 para 1er año, 2 para 2do año).",
                        verbose_name="Orden dentro del Nivel",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_levels",
                        to="core.level",
                        verbose_name="Nivel Educativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grado/Año de Estudio",
                "verbose_name_plural": "Grados/Años de Estudio",
                "ordering": ["level__name", "order_in_level", "name"],
                "unique_together": {("level", "name")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="subjectassignment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="section",
            name="grade_level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="core.gradelevel",
                verbose_name="Grado/Año de Estudio",
            ),
        ),
        migrations.AddField(
            model_name="subjectassignment",
            name="grade_level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_assignments",
                to="core.gradelevel",
                verbose_name="Grado/Año de Estudio",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("name", "grade_level", "academic_year")},
        ),
        migrations.AlterUniqueTogether(
            name="subjectassignment",
            unique_together={("subject", "grade_level")},
        ),
        migrations.RemoveField(
            model_name="studentenrollment",
            name="academic_period",
        ),
        migrations.RemoveField(
            model_name="subjectassignment",
            name="academic_year",
        ),
    ]
