# Generated by Django 5.2.3 on 2025-06-20 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_evaluation_placeholders"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuideTeacherAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guide_teacher_assignment",
                        to="core.section",
                        verbose_name="Sección Asignada como Guía",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "TEACHER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guide_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Profesor(a) Guía",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Profesor Guía",
                "verbose_name_plural": "Asignaciones de Profesores Guías",
                "ordering": [
                    "section__academic_year__name",
                    "section__grade_level__order_in_level",
                    "section__name",
                ],
            },
        ),
        migrations.CreateModel(
            name="CoordinatorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinators",
                        to="core.academicyear",
                        verbose_name="Año Académico de Coordinación",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinators",
                        to="core.level",
                        verbose_name="Nivel Educativo Coordinado",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["TEACHER", "DIRECTOR", "ADMIN"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinator_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coordinador(a)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Coordinador de Nivel",
                "verbose_name_plural": "Asignaciones de Coordinadores de Nivel",
                "ordering": [
                    "academic_year__name",
                    "level__name",
                    "teacher__last_name",
                ],
                "unique_together": {("teacher", "level", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="StudentGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones Adicionales"
                    ),
                ),
                (
                    "submission_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro de Nota"
                    ),
                ),
                (
                    "academic_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_grades",
                        to="core.academicperiod",
                        verbose_name="Lapso Académico",
                    ),
                ),
                (
                    "grade_value",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_grades",
                        to="core.gradevalue",
                        verbose_name="Calificación Obtenida",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["TEACHER", "ADMIN"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grades_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Calificado Por",
                    ),
                ),
                (
                    "student_enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="core.studentenrollment",
                        verbose_name="Inscripción del Estudiante",
                    ),
                ),
                (
                    "subject_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_grades",
                        to="core.subjectassignment",
                        verbose_name="Materia Calificada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calificación de Estudiante",
                "verbose_name_plural": "Calificaciones de Estudiantes",
                "ordering": [
                    "student_enrollment__student__last_name",
                    "subject_assignment__subject__name",
                    "academic_period__start_date",
                ],
                "unique_together": {
                    ("student_enrollment", "subject_assignment", "academic_period")
                },
            },
        ),
        migrations.CreateModel(
            name="TeacherSubjectSectionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_allocations",
                        to="core.section",
                        verbose_name="Sección Específica",
                    ),
                ),
                (
                    "subject_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_allocations",
                        to="core.subjectassignment",
                        verbose_name="Asignatura y Grado Asignado",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "TEACHER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_subject_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Profesor(a)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Materia a Profesor por Sección",
                "verbose_name_plural": "Asignaciones de Materias a Profesores por Sección",
                "ordering": [
                    "teacher__last_name",
                    "teacher__first_name",
                    "subject_assignment__subject__name",
                    "section__name",
                ],
                "unique_together": {("teacher", "subject_assignment", "section")},
            },
        ),
    ]
