# Generated by Django 4.2.23 on 2025-06-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_chatroom_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicperiod",
            name="report_cards_released",
            field=models.BooleanField(
                default=False,
                help_text="Marcar si las boletas/calificaciones finales para este lapso han sido publicadas.",
                verbose_name="Boletas Liberadas",
            ),
        ),
    ]
