# Generated by Django 5.2.3 on 2025-06-23 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_academicperiod_report_cards_released"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="name",
            field=models.CharField(
                choices=[
                    ("inicial", "Educación inicial"),
                    ("primaria", "Educación primaria"),
                    ("media_general", "Educación media general"),
                    ("asp", "ASP"),
                    ("extracurricular", "Extracurriculares"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Nombre",
            ),
        ),
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Promedio General",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "academic_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="core.academicperiod",
                        verbose_name="Lapso Académico",
                    ),
                ),
                (
                    "student_enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="core.studentenrollment",
                        verbose_name="Inscripción del Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boleta de Calificaciones",
                "verbose_name_plural": "Boletas de Calificaciones",
                "ordering": ["student_enrollment", "academic_period__start_date"],
                "unique_together": {("student_enrollment", "academic_period")},
            },
        ),
        migrations.CreateModel(
            name="ReportCardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_grade_numeric",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Nota Definitiva Numérica",
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "final_grade_qualitative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_card_qualitative_entries",
                        to="core.gradevalue",
                        verbose_name="Nota Definitiva Cualitativa (Opcional)",
                    ),
                ),
                (
                    "report_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="core.reportcard",
                        verbose_name="Boleta",
                    ),
                ),
                (
                    "subject_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_card_entries",
                        to="core.subjectassignment",
                        verbose_name="Asignatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de Boleta",
                "verbose_name_plural": "Entradas de Boleta",
                "ordering": ["subject_assignment__subject__name"],
                "unique_together": {("report_card", "subject_assignment")},
            },
        ),
    ]
