# Generated by Django 4.2.23 on 2025-06-24 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_level_name_reportcard_reportcardentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Mi Colegio",
                        max_length=255,
                        verbose_name="Nombre del Colegio",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="school_logos/",
                        verbose_name="Logo del Colegio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración General del Colegio",
                "verbose_name_plural": "Configuración General del Colegio",
            },
        ),
        migrations.AlterModelOptions(
            name="gradevalue",
            options={
                "ordering": ["scale__name", "order", "numeric_equivalent"],
                "verbose_name": "Valor de Calificación",
                "verbose_name_plural": "Valores de Calificación",
            },
        ),
        migrations.AlterModelOptions(
            name="gradingscale",
            options={
                "ordering": ["name"],
                "verbose_name": "Escala de Calificación",
                "verbose_name_plural": "Escalas de Calificación",
            },
        ),
        migrations.AlterModelOptions(
            name="level",
            options={
                "ordering": ["name"],
                "verbose_name": "Nivel Educativo",
                "verbose_name_plural": "Niveles Educativos",
            },
        ),
        migrations.AlterModelOptions(
            name="placeholdereducacionbasica",
            options={
                "verbose_name": "Marcador de Posición: Evaluación Básica",
                "verbose_name_plural": "Marcadores de Posición: Evaluación Básica",
            },
        ),
        migrations.AlterModelOptions(
            name="placeholdereducacionmediageneral",
            options={
                "verbose_name": "Marcador de Posición: Evaluación Media General",
                "verbose_name_plural": "Marcadores de Posición: Evaluación Media General",
            },
        ),
        migrations.AlterModelOptions(
            name="placeholdereducacionprimaria",
            options={
                "verbose_name": "Marcador de Posición: Evaluación Primaria",
                "verbose_name_plural": "Marcadores de Posición: Evaluación Primaria",
            },
        ),
        migrations.AlterModelOptions(
            name="preenrollmentprofile",
            options={
                "ordering": [
                    "-fecha_preinscripcion",
                    "apellidos_alumno",
                    "nombres_alumno",
                ],
                "verbose_name": "Perfil de Preinscripción",
                "verbose_name_plural": "Perfiles de Preinscripción",
            },
        ),
        migrations.AlterModelOptions(
            name="reportcard",
            options={
                "ordering": [
                    "student_enrollment__student__last_name",
                    "academic_period__start_date",
                ],
                "verbose_name": "Boletín de Calificaciones",
                "verbose_name_plural": "Boletines de Calificaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="reportcardentry",
            options={
                "ordering": ["report_card", "subject_assignment__subject__name"],
                "verbose_name": "Detalle de Boletín (por Asignatura)",
                "verbose_name_plural": "Detalles de Boletines (por Asignatura)",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ["name"],
                "verbose_name": "Asignatura",
                "verbose_name_plural": "Asignaturas",
            },
        ),
        migrations.AlterModelOptions(
            name="teachersubjectsectionassignment",
            options={
                "ordering": [
                    "teacher__last_name",
                    "teacher__first_name",
                    "subject_assignment__subject__name",
                    "section__name",
                ],
                "verbose_name": "Asignación Profesor-Asignatura-Sección",
                "verbose_name_plural": "Asignaciones Profesor-Asignatura-Sección",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="content",
            field=models.TextField(verbose_name="Contenido"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="core.chatroom",
                verbose_name="Sala",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Enviado el"),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creada el"),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Nombre de la Sala"
            ),
        ),
        migrations.AlterField(
            model_name="gradevalue",
            name="display_value",
            field=models.CharField(
                max_length=20, verbose_name="Valor Visible (ej: A, B, 20, Aprobado)"
            ),
        ),
        migrations.AlterField(
            model_name="gradevalue",
            name="numeric_equivalent",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Equivalente Numérico"
            ),
        ),
        migrations.AlterField(
            model_name="gradevalue",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Orden para mostrar en listas/desplegables",
                verbose_name="Orden de Visualización",
            ),
        ),
        migrations.AlterField(
            model_name="gradevalue",
            name="scale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="core.gradingscale",
                verbose_name="Escala Asociada",
            ),
        ),
        migrations.AlterField(
            model_name="gradingscale",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="gradingscale",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Nombre de la Escala"
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="name",
            field=models.CharField(
                choices=[
                    ("inicial", "Educación Inicial"),
                    ("primaria", "Educación Primaria"),
                    ("media_general", "Educación Media General"),
                    ("asp", "ASP (Actividades Socio-Productivas)"),
                    ("extracurricular", "Actividades Extracurriculares"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Nombre del Nivel",
            ),
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creada el"),
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizada el"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Nombre de la Asignatura"
            ),
        ),
        migrations.AlterField(
            model_name="teachersubjectsectionassignment",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_teachers_subjects",
                to="core.section",
                verbose_name="Sección Específica",
            ),
        ),
        migrations.AlterField(
            model_name="teachersubjectsectionassignment",
            name="subject_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_section_assignments",
                to="core.subjectassignment",
                verbose_name="Asignatura y Grado/Año",
            ),
        ),
        migrations.AlterField(
            model_name="teachersubjectsectionassignment",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"role": "TEACHER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_section_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Profesor(a)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("TEACHER", "Profesor"),
                    ("STUDENT", "Estudiante"),
                    ("PARENT", "Representante"),
                    ("DIRECTOR", "Director"),
                ],
                default="STUDENT",
                max_length=10,
                verbose_name="Rol",
            ),
        ),
    ]
