# Generated by Django 4.2.23 on 2025-06-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_schoolconfiguration_alter_gradevalue_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Foto de perfil del usuario.",
                null=True,
                upload_to="profile_pics/",
                verbose_name="Foto de Perfil",
            ),
        ),
    ]
