# Generated by Django 4.2.23 on 2025-06-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicperiod",
            name="name",
            field=models.CharField(
                choices=[
                    ("1ER_LAPSO", "1er Lapso"),
                    ("2DO_LAPSO", "2do Lapso"),
                    ("3ER_LAPSO", "3er Lapso"),
                    ("VACACIONES", "Vacaciones"),
                ],
                max_length=20,
                verbose_name="Nombre del Lapso",
            ),
        ),
    ]
