@echo off
echo Starting Django development server...
echo Navigating to Django project directory (school_management_system)...
cd school_management_system
echo Running manage.py runserver...
python manage.py runserver
echo Server stopped.
pause
