# Generated by Django 4.2.23 on 2025-06-22 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teachers", "0003_evaluationactivity_evaluationplandocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_file",
                    models.FileField(
                        upload_to=students.models.student_submission_path,
                        verbose_name="Archivo Enviado",
                    ),
                ),
                (
                    "submission_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Envío"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Notas Adicionales del Estudiante",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="teachers.activity",
                        verbose_name="Actividad",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega de Estudiante",
                "verbose_name_plural": "Entregas de Estudiantes",
                "ordering": ["-submission_date"],
                "unique_together": {("student", "activity")},
            },
        ),
    ]
