# Generated by Django 5.2.3 on 2025-06-18 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_teacher_assignments",
                        to="core.section",
                        verbose_name="Section",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_teacher_assignments",
                        to="core.subject",
                        verbose_name="Subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "TEACHER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Assignment",
                "verbose_name_plural": "Teacher Assignments",
                "unique_together": {("teacher", "subject", "section")},
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due Date"),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Max Score (e.g., 20, 100)"
                    ),
                ),
                (
                    "academic_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="period_activities",
                        to="core.academicperiod",
                        verbose_name="Academic Period (for grading window)",
                    ),
                ),
                (
                    "teacher_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="teachers.teacherassignment",
                        verbose_name="Teacher Assignment (Subject/Section)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "ordering": ["teacher_assignment", "due_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Score",
                    ),
                ),
                (
                    "submission_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Submission/Grading Date"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="Feedback"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="teachers.activity",
                        verbose_name="Activity",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
                "ordering": [
                    "activity__teacher_assignment__section__academic_year",
                    "activity__teacher_assignment__subject",
                    "activity__title",
                    "student__last_name",
                    "student__first_name",
                ],
                "unique_together": {("student", "activity")},
            },
        ),
    ]
