# Generated by Django 5.2.3 on 2025-06-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("PRESENCIAL", "Presencial (In-person)"),
                    ("ONLINE", "En Línea (Online)"),
                ],
                default="PRESENCIAL",
                help_text="Seleccione si la actividad es presencial o en línea.",
                max_length=20,
                verbose_name="Tipo de Actividad",
            ),
        ),
    ]
