# Generated by Django 5.2.3 on 2025-06-19 14:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0002_activity_activity_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Activity Name"),
                ),
                ("date", models.DateField(verbose_name="Activity Date")),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of the total grade (0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Percentage",
                    ),
                ),
                (
                    "teacher_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_activities",
                        to="teachers.teacherassignment",
                        verbose_name="Teacher Assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluation Activity",
                "verbose_name_plural": "Evaluation Activities",
                "ordering": ["teacher_assignment", "date", "name"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationPlanDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="evaluation_plans/", verbose_name="File"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "teacher_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_plan_documents",
                        to="teachers.teacherassignment",
                        verbose_name="Teacher Assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluation Plan Document",
                "verbose_name_plural": "Evaluation Plan Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
