# Generated by Django 5.2.3 on 2025-06-18 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_academicperiod_options_and_more"),
        ("teachers", "0002_alter_teacherassignment_subject_activity_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="academic_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="period_activities",
                to="core.academicperiod",
                verbose_name="Academic Period (for grading window)",
            ),
        ),
    ]
