# Generated by Django 4.2.23 on 2025-06-23 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0003_evaluationactivity_evaluationplandocument"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["teacher_assignment", "due_date", "title"],
                "verbose_name": "Actividad",
                "verbose_name_plural": "Activities",
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="allow_late_submissions",
            field=models.BooleanField(
                default=False,
                help_text="Si se marca, los estudiantes podrán enviar trabajos después de la fecha de entrega.",
                verbose_name="Permitir entregas tardías",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationactivity",
            name="percentage",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Porcentaje sobre la calificación total (0-100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Porcentaje",
            ),
        ),
    ]
