# Generated by Django 4.2.23 on 2025-06-24 15:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0010_schoolconfiguration_alter_gradevalue_options_and_more"),
        ("teachers", "0004_alter_activity_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": [
                    "teacher_assignment__section__academic_year__start_date",
                    "teacher_assignment__subject__name",
                    "due_date",
                    "title",
                ],
                "verbose_name": "Actividad Evaluativa",
                "verbose_name_plural": "Actividades Evaluativas",
            },
        ),
        migrations.AlterModelOptions(
            name="evaluationactivity",
            options={
                "ordering": ["academic_period", "teacher_assignment", "date", "name"],
                "verbose_name": "Actividad Planificada (Plan de Evaluación)",
                "verbose_name_plural": "Actividades Planificadas (Planes de Evaluación)",
            },
        ),
        migrations.AlterModelOptions(
            name="evaluationplandocument",
            options={
                "ordering": ["teacher_assignment", "-uploaded_at"],
                "verbose_name": "Documento de Plan de Evaluación",
                "verbose_name_plural": "Documentos de Planes de Evaluación",
            },
        ),
        migrations.AlterModelOptions(
            name="grade",
            options={
                "ordering": [
                    "activity__teacher_assignment__section__academic_year",
                    "activity__teacher_assignment__subject",
                    "activity__title",
                    "student__last_name",
                    "student__first_name",
                ],
                "verbose_name": "Calificación de Actividad",
                "verbose_name_plural": "Calificaciones de Actividades",
            },
        ),
        migrations.AlterModelOptions(
            name="teacherassignment",
            options={
                "ordering": ["teacher__last_name", "subject__name", "section__name"],
                "verbose_name": "Asignación de Profesor a Asignatura/Sección",
                "verbose_name_plural": "Asignaciones de Profesores a Asignaturas/Secciones",
            },
        ),
        migrations.AddField(
            model_name="evaluationactivity",
            name="academic_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluation_plan_activities",
                to="core.academicperiod",
                verbose_name="Lapso Académico",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="academic_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="period_activities",
                to="core.academicperiod",
                verbose_name="Lapso Académico Asociado",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("PRESENCIAL", "Presencial"),
                    ("ONLINE", "En Línea"),
                    ("HIBRIDA", "Híbrida"),
                    ("PROYECTO", "Proyecto"),
                    ("EXAMEN", "Examen/Prueba"),
                ],
                default="PRESENCIAL",
                help_text="Seleccione la modalidad o tipo principal de la actividad.",
                max_length=20,
                verbose_name="Modalidad/Tipo de Actividad",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="allow_late_submissions",
            field=models.BooleanField(
                default=False,
                help_text="Si se marca, los estudiantes podrán enviar trabajos después de la fecha límite (si aplica).",
                verbose_name="Permitir Entregas Tardías",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción Detallada"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Entrega/Realización"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="max_score",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Puntaje Máximo (ej: 20, 100)"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="teacher_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="teachers.teacherassignment",
                verbose_name="Asignación (Profesor-Asignatura-Sección)",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="title",
            field=models.CharField(
                max_length=200, verbose_name="Título de la Actividad"
            ),
        ),
        migrations.AlterField(
            model_name="evaluationactivity",
            name="date",
            field=models.DateField(verbose_name="Fecha Estimada/Límite"),
        ),
        migrations.AlterField(
            model_name="evaluationactivity",
            name="name",
            field=models.CharField(
                max_length=200, verbose_name="Nombre de la Actividad Planificada"
            ),
        ),
        migrations.AlterField(
            model_name="evaluationactivity",
            name="percentage",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Porcentaje sobre la calificación final del lapso (0-100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="Ponderación (%)",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationactivity",
            name="teacher_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planned_evaluation_activities",
                to="teachers.teacherassignment",
                verbose_name="Asignación (Profesor-Asignatura-Sección)",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationplandocument",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descripción Breve"
            ),
        ),
        migrations.AlterField(
            model_name="evaluationplandocument",
            name="file",
            field=models.FileField(
                upload_to="evaluation_plans/",
                verbose_name="Archivo del Plan de Evaluación",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationplandocument",
            name="teacher_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluation_plan_documents",
                to="teachers.teacherassignment",
                verbose_name="Asignación (Profesor-Asignatura-Sección)",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationplandocument",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Carga"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_grades_for_activity",
                to="teachers.activity",
                verbose_name="Actividad Evaluada",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="feedback",
            field=models.TextField(
                blank=True, null=True, verbose_name="Comentarios/Retroalimentación"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Calificación/Puntaje Obtenido",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "STUDENT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades_received_detailed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Estudiante",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="submission_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Calificación/Registro"
            ),
        ),
        migrations.AlterField(
            model_name="teacherassignment",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_assignments_for_section",
                to="core.section",
                verbose_name="Sección",
            ),
        ),
        migrations.AlterField(
            model_name="teacherassignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_assignments_for_subject",
                to="core.subject",
                verbose_name="Asignatura",
            ),
        ),
        migrations.AlterField(
            model_name="teacherassignment",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"role": "TEACHER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments_as_teacher",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Profesor(a)",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evaluationactivity",
            unique_together={("teacher_assignment", "name", "academic_period")},
        ),
    ]
