"""
Django settings for school_management_system project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os # Added for LOCALE_PATHS
from pathlib import Path
from django.utils.translation import gettext_lazy as _ # Added for LANGUAGES

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%ii3@v7tyj=8x6u)i6=+!kkyy08@yn$2)v(41z6s19q0+(%@53"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "students",
    "teachers",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'django.middleware.locale.LocaleMiddleware', # Added here
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "school_management_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.school_settings_processor", # Added context processor
            ],
        },
    },
]

WSGI_APPLICATION = "school_management_system.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es' # Changed to Spanish

LANGUAGES = [
    ('es', _('Spanish')),
    ('en', _('English')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

TIME_ZONE = "UTC"

USE_I18N = True
# USE_L10N = True # This is the default and often not explicitly set, but ensuring it's effectively True
# Django 4.0+ uses USE_L10N = True by default. If it's not here, it's fine.

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'core.User'

# LOGIN_REDIRECT_URL = '/student/dashboard/'
LOGIN_REDIRECT_URL = '/' # Default to home page
LOGOUT_REDIRECT_URL = '/'

# Media files (User-uploaded files)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Custom School Settings (example)
SCHOOL_NAME = "Nombre de Mi Colegio"
# SCHOOL_LOGO_URL = STATIC_URL + "images/school_logo.png" # Example if you have a logo in static/images
SCHOOL_LOGO_URL = None # Set to your logo's path or None

JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Admin del Colegio",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Mi Colegio",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Mi Colegio",

    # Logo to use for your site, must be present in static files, used for brand on top left
    # "site_logo": "images/logo.png",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": None,

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": None,

    # Welcome text on the login screen
    "welcome_sign": "Bienvenido a la Administración de Mi Colegio",

    # Copyright on the footer
    "copyright": "Mi Colegio Ltd.",

    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string
    "search_model": ["core.User"],

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Inicio",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # external url that opens in a new window (Permissions can be added)
        # {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        # {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": False,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [], # We are not hiding full apps, but ordering models from them

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [
        "core.ReportCardEntry",
        "core.PlaceholderEducacionMediaGeneral",
        "core.PlaceholderEducacionPrimaria",
        "core.PlaceholderEducacionBasica"
    ],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": [
        # 1. Configuración General
        "core.SchoolConfiguration", # Configuración General del Colegio
        "core.Subject",             # Asignatura

        # 2. Autenticación y Usuarios
        "auth", # App 'auth' (Usuarios, Grupos)

        # 3. Administración de Evaluación (Modelos de 'core', agrupados por custom_links)
        # Estos modelos se listan aquí para que Jazzmin los conozca;
        # `custom_links` controlará su agrupación y etiquetado.
        "core.AcademicYear",
        "core.SubjectAssignment", # Asignación de Materia a Grado
        "core.GradeLevel",
        "core.AcademicPeriod",    # Lapso Académico
        "core.Level",
        "core.Section",

        # 4. Inscripciones (Modelos de 'core', agrupados por custom_links)
        "core.StudentEnrollment",    # Inscripción de Estudiante
        "core.PreEnrollmentProfile", # Perfil de Preinscripción

        # 5. Evaluación de Bachillerato (Modelos de 'core', agrupados por custom_links)
        "core.GuideTeacherAssignment", # Asignación de Profesor Guía
        "core.TeacherSubjectSectionAssignment", # Asignación Profesor-Asignatura-Sección
        "core.ReportCard",          # Boletín de Calificaciones
        "core.StudentGrade",        # Calificación de Estudiante
        "core.GradingScale",        # Escala de Calificación
        "core.GradeValue",          # Valor de Calificación

        # 6. Gestión de Estudiantes
        "students.StudentSubmission", # Entregas de Estudiantes (de app 'students')
        # Si hay otros modelos de la app 'students' o 'core' que van aquí, listarlos.

        # 7. Gestión de Personal
        "core.CoordinatorAssignment", # Asignación de Coordinador de Nivel

        # 8. Comunicación
        "core.ChatMessage", # Mensaje de Chat
        "core.ChatRoom",    # Sala de Chat
    ],

    "custom_links": {
        "core": [
            {
                "name": _("Administración de evaluación"),
                "url": "javascript:void(0);",
                "icon": "fas fa-cogs",
                "children": [
                    # Ordenados alfabéticamente por verbose_name
                    {"model": "core.academicyear", "label": _("Año Académico"), "icon": "fas fa-calendar-alt"},
                    {"model": "core.subjectassignment", "label": _("Asignación de Materia a Grado"), "icon": "fas fa-tasks"},
                    {"model": "core.gradelevel", "label": _("Grado/Año de Estudio"), "icon": "fas fa-graduation-cap"},
                    {"model": "core.academicperiod", "label": _("Lapso Académico"), "icon": "fas fa-clock"},
                    {"model": "core.level", "label": _("Nivel Educativo"), "icon": "fas fa-layer-group"},
                    {"model": "core.section", "label": _("Sección"), "icon": "fas fa-chalkboard-teacher"},
                ],
                "permissions": ["core.view_academicyear"],
            },
            {
                "name": _("Evaluación de bachillerato"),
                "url": "javascript:void(0);",
                "icon": "fas fa-award",
                "children": [
                    # Ordenados alfabéticamente por verbose_name
                    {"model": "core.guideteacherassignment", "label": _("Asignación de Profesor Guía"), "icon": "fas fa-user-tie"},
                    {"model": "core.teachersubjectsectionassignment", "label": _("Asignación Profesor-Asignatura-Sección"), "icon": "fas fa-chalkboard-user"},
                    {"model": "core.reportcard", "label": _("Boletín de Calificaciones"), "icon": "fas fa-file-invoice"},
                    {"model": "core.studentgrade", "label": _("Calificación de Estudiante"), "icon": "fas fa-award"},
                    {"model": "core.gradingscale", "label": _("Escala de Calificación"), "icon": "fas fa-balance-scale"},
                    {"model": "core.gradevalue", "label": _("Valor de Calificación"), "icon": "fas fa-star-half-alt"},
                ],
                "permissions": ["core.view_gradingscale"],
            },
            {
                "name": _("Inscripciones"),
                "url": "javascript:void(0);",
                "icon": "fas fa-user-plus",
                "children": [
                    # Ordenados alfabéticamente por verbose_name
                    {"model": "core.studentenrollment", "label": _("Inscripción de Estudiante"), "icon": "fas fa-user-check"},
                    {"model": "core.preenrollmentprofile", "label": _("Perfil de Preinscripción"), "icon": "fas fa-id-card-alt"},
                ],
                "permissions": ["core.view_preenrollmentprofile"],
            },
            # Modelos de 'core' que no están en grupos personalizados y deben aparecer bajo "Core"
            # (si 'core' no está en hide_apps)
            # Si todos los modelos de 'core' están en los grupos de arriba, no es necesario más aquí para 'core'.
            # Los modelos de 'core' que SÍ queremos bajo el encabezado "Core" (o su verbose_name)
            # y que NO están en los grupos personalizados, deben estar en `order_with_respect_to`.
            # Jazzmin quita los modelos de `custom_links` de su lugar natural.
            # Los modelos que quedan en `order_with_respect_to` para 'core' (como SchoolConfiguration, Subject, CoordinatorAssignment, ChatMessage, ChatRoom)
            # se agruparán bajo la app "Core".
            # Para ordenar estos alfabéticamente:
            # SchoolConfiguration: "Configuración General del Colegio"
            # Subject: "Asignatura"
            # CoordinatorAssignment: "Asignación de Coordinador de Nivel"
            # ChatMessage: "Mensaje de Chat"
            # ChatRoom: "Sala de Chat"
            # Orden: Asignatura, Asignación de Coordinador de Nivel, Configuración General del Colegio, Mensaje de Chat, Sala de Chat
            # Este orden se refleja en `order_with_respect_to`.
        ],
        "students": [
            # Para "Gestión de Estudiantes" si solo contiene StudentSubmission:
            {"model": "students.studentsubmission", "label": _("Entregas de Actividades por Estudiantes"), "icon": "fas fa-file-upload"}
        ],
        "auth": [ # Para ordenar "auth" alfabéticamente si es necesario
            {"model": "auth.group", "label": _("Grupos"), "icon": "fas fa-users"},
            {"model": "auth.user", "label": _("Usuarios"), "icon": "fas fa-user"},
        ]
    },
    # Asegurarse que los modelos en `custom_links` usan minúsculas para `model: "app.modelname"`

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5
    # for a list of icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core": "fas fa-school", # Icono genérico para la app 'core' si se muestra como grupo

        # Iconos para modelos en Configuración General
        "core.SchoolConfiguration": "fas fa-cogs",
        "core.Subject": "fas fa-book",

        # Iconos para modelos en ADMINISTRACIÓN DE EVALUACIÓN
        "core.AcademicYear": "fas fa-calendar-alt",
        "core.AcademicPeriod": "fas fa-clock",
        "core.Level": "fas fa-layer-group",
        "core.GradeLevel": "fas fa-graduation-cap",
        "core.Section": "fas fa-chalkboard-teacher", # Reutilizado, podría ser más específico si es necesario
        "core.SubjectAssignment": "fas fa-tasks",

        # Iconos para modelos en EVALUACIÓN DE BACHILLERATO
        "core.GradingScale": "fas fa-balance-scale",
        "core.GradeValue": "fas fa-star-half-alt",
        "core.GuideTeacherAssignment": "fas fa-user-tie",
        "core.TeacherSubjectSectionAssignment": "fas fa-chalkboard-user", # Icono más específico para esta asignación
        "core.StudentGrade": "fas fa-award",
        "core.ReportCard": "fas fa-file-invoice",


        # Iconos para modelos en Estudiantes (los que quedan o son de la app students)
        "students": "fas fa-user-friends", # App icon for "Estudiantes"
        "core.PreEnrollmentProfile": "fas fa-id-card",
        "core.StudentEnrollment": "fas fa-user-graduate",
        "students.StudentSubmission": "fas fa-file-upload", # Model in students app

        # Iconos para modelos en Gestión de Personal
        "core.CoordinatorAssignment": "fas fa-sitemap",

        # Iconos para Comunicación
        "core.ChatRoom": "fas fa-comments",
        "core.ChatMessage": "fas fa-comment-dots",

        # Iconos para la app teachers si se usa
        "teachers": "fas fa-chalkboard-teacher", # Icono genérico para la app 'teachers'
        # "teachers.TeacherAssignment": "fas fa-address-book", # Ejemplo si existiera este modelo en la app teachers
        # "teachers.Activity": "fas fa-pencil-ruler",
        # "teachers.Grade": "fas fa-marker",

        # Modelos ocultos (aunque se muevan, si estaban ocultos y deben seguir así, mantenerlos)
        "core.ReportCardEntry": "fas fa-list-ol", # Icono por si se muestra en otro lado
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": "css/admin_customizations.css",
    "custom_js": None,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,

    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    "language_chooser": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True, # Para hacer el cuerpo del texto un poco más pequeño
    "brand_small_text": False,
    "brand_colour": "navbar-primary", # Color primario para la marca
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light", # Barra de navegación clara
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary", # Barra lateral oscura con acento primario
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False, # Estilo plano para la navegación lateral
    "theme": "default", # Tema por defecto, se puede cambiar a otros como "cerulean", "cosmo", "flatly", "journal", "litera", "lumen", "lux", "materia", "minty", "pulse", "sandstone", "simplex", "sketchy", "slate", "solar", "spacelab", "superhero", "united", "yeti"
    "dark_mode_theme": None, # Se puede poner un tema específico para modo oscuro
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True # Hacer que la barra de acciones sea pegajosa
}
