"""
Django settings for school_management_system project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os # Added for LOCALE_PATHS
from pathlib import Path
from django.utils.translation import gettext_lazy as _ # Added for LANGUAGES

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%ii3@v7tyj=8x6u)i6=+!kkyy08@yn$2)v(41z6s19q0+(%@53"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "students",
    "teachers",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'django.middleware.locale.LocaleMiddleware', # Added here
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "school_management_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.school_settings_processor", # Added context processor
            ],
        },
    },
]

WSGI_APPLICATION = "school_management_system.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es' # Changed to Spanish

LANGUAGES = [
    ('es', _('Spanish')),
    ('en', _('English')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

TIME_ZONE = "UTC"

USE_I18N = True
# USE_L10N = True # This is the default and often not explicitly set, but ensuring it's effectively True
# Django 4.0+ uses USE_L10N = True by default. If it's not here, it's fine.

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'core.User'

# LOGIN_REDIRECT_URL = '/student/dashboard/'
LOGIN_REDIRECT_URL = '/' # Default to home page
LOGOUT_REDIRECT_URL = '/'

# Media files (User-uploaded files)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Custom School Settings (example)
SCHOOL_NAME = "Nombre de Mi Colegio"
# SCHOOL_LOGO_URL = STATIC_URL + "images/school_logo.png" # Example if you have a logo in static/images
SCHOOL_LOGO_URL = None # Set to your logo's path or None

JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Admin del Colegio",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Mi Colegio",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Mi Colegio",

    # Logo to use for your site, must be present in static files, used for brand on top left
    # "site_logo": "images/logo.png",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": None,

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": None,

    # Welcome text on the login screen
    "welcome_sign": "Bienvenido a la Administración de Mi Colegio",

    # Copyright on the footer
    "copyright": "Mi Colegio Ltd.",

    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string
    "search_model": ["core.User"],

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Inicio",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # external url that opens in a new window (Permissions can be added)
        # {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        # {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": False,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [], # We are not hiding full apps, but ordering models from them

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [
        "core.ReportCardEntry",
        "core.PlaceholderEducacionMediaGeneral",
        "core.PlaceholderEducacionPrimaria",
        "core.PlaceholderEducacionBasica"
    ],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": [
        # Configuración General
        "core.SchoolConfiguration",
        "core.Subject",

        # Autenticación y Autorización
        "auth", # Esto mostrará la app 'auth' con sus modelos (User, Group)

        # ADMINISTRACIÓN DE EVALUACIÓN
        # Estos son modelos de la app 'core'. Jazzmin los agrupará bajo 'Core' (o su verbose_name).
        # La etiqueta personalizada "ADMINISTRACIÓN DE EVALUACIÓN" se logrará con `custom_links`.
        "core.AcademicYear",
        "core.AcademicPeriod",
        "core.Level",
        "core.GradeLevel",
        "core.Section",
        "core.SubjectAssignment",

        # EVALUACIÓN DE BACHILLERATO
        # Estos también son modelos de la app 'core'.
        "core.GradingScale",
        "core.GradeValue",
        "core.GuideTeacherAssignment",
        "core.TeacherSubjectSectionAssignment",
        "core.StudentGrade",
        "core.ReportCard",

        # Gestión de Estudiantes (Modelos de 'core' y 'students')
        # Para modelos de 'core' que van aquí:
        "core.PreEnrollmentProfile",
        "core.StudentEnrollment",
        # Para modelos de la app 'students':
        "students.StudentSubmission", # Asumiendo que es el único modelo visible de la app 'students'
        # Si hay más modelos en la app 'students' y se quieren todos juntos, se puede usar "students" como string.

        # Gestión de Personal
        "core.CoordinatorAssignment",

        # Comunicación
        "core.ChatRoom",
        "core.ChatMessage",

        # Si la app 'teachers' tiene modelos que mostrar, se añadiría "teachers" aquí.
    ],

    "custom_links": {
        "core": [
            {
                "name": _("ADMINISTRACIÓN DE EVALUACIÓN"), # Usar gettext_lazy para traducción
                "url": "javascript:void(0);", # URL no funcional, solo para agrupar
                "icon": "fas fa-cogs", # Icono para el grupo
                "children": [
                    {"model": "core.academicyear", "icon": "fas fa-calendar-alt"},
                    {"model": "core.academicperiod", "icon": "fas fa-clock"},
                    {"model": "core.level", "icon": "fas fa-layer-group"},
                    {"model": "core.gradelevel", "icon": "fas fa-graduation-cap"},
                    {"model": "core.section", "icon": "fas fa-chalkboard-teacher"},
                    {"model": "core.subjectassignment", "icon": "fas fa-tasks"},
                ],
                # Permiso para ver el grupo, podría ser el de ver el primer modelo del grupo
                "permissions": ["core.view_academicyear"],
            },
            {
                "name": _("EVALUACIÓN DE BACHILLERATO"),
                "url": "javascript:void(0);",
                "icon": "fas fa-award", # Icono para el grupo
                "children": [
                    {"model": "core.gradingscale", "icon": "fas fa-balance-scale"},
                    {"model": "core.gradevalue", "icon": "fas fa-star-half-alt"},
                    {"model": "core.guideteacherassignment", "icon": "fas fa-user-tie"},
                    {"model": "core.teachersubjectsectionassignment", "icon": "fas fa-chalkboard-user"},
                    {"model": "core.studentgrade", "icon": "fas fa-award"}, # Reutilizado, o fas fa-clipboard-check
                    {"model": "core.reportcard", "icon": "fas fa-file-invoice"},
                ],
                "permissions": ["core.view_gradingscale"],
            },
            # Si hay otros modelos de 'core' que no están en estos grupos y quieres que aparezcan
            # bajo un encabezado 'Core' genérico, Jazzmin podría hacerlo por defecto si la app 'core'
            # no está en 'hide_apps' y los modelos no están cubiertos por `custom_links` que los "mueven".
            # Para evitar que los modelos aparezcan dos veces (en custom_links y bajo la app 'core' por defecto),
            # a veces es necesario ocultar la app original con `hide_apps = ['core']`
            # y luego construir todo el menú de 'core' con `custom_links`.
            # O, asegurarse que `order_with_respect_to` liste los modelos que NO están en custom_links.
            # La interacción puede ser compleja.
            # La documentación de Jazzmin dice: "Custom links are added to the app group, if the app is not hidden".
            # "Models included in custom_links will be removed from the app list where they would normally appear."
            # Esto es bueno, significa que no deberíamos tener duplicados.
        ],
        # Si queremos renombrar el grupo de la app "students" o añadirle cosas:
        # "students": [
        # { "name": _("Gestión Integral de Estudiantes"), ...}
        # ]
    },
    # Asegurarse que los modelos en `custom_links` usan minúsculas para `model: "app.modelname"`

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5
    # for a list of icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core": "fas fa-school", # Icono genérico para la app 'core' si se muestra como grupo

        # Iconos para modelos en Configuración General
        "core.SchoolConfiguration": "fas fa-cogs",
        "core.Subject": "fas fa-book",

        # Iconos para modelos en ADMINISTRACIÓN DE EVALUACIÓN
        "core.AcademicYear": "fas fa-calendar-alt",
        "core.AcademicPeriod": "fas fa-clock",
        "core.Level": "fas fa-layer-group",
        "core.GradeLevel": "fas fa-graduation-cap",
        "core.Section": "fas fa-chalkboard-teacher", # Reutilizado, podría ser más específico si es necesario
        "core.SubjectAssignment": "fas fa-tasks",

        # Iconos para modelos en EVALUACIÓN DE BACHILLERATO
        "core.GradingScale": "fas fa-balance-scale",
        "core.GradeValue": "fas fa-star-half-alt",
        "core.GuideTeacherAssignment": "fas fa-user-tie",
        "core.TeacherSubjectSectionAssignment": "fas fa-chalkboard-user", # Icono más específico para esta asignación
        "core.StudentGrade": "fas fa-award",
        "core.ReportCard": "fas fa-file-invoice",


        # Iconos para modelos en Estudiantes (los que quedan o son de la app students)
        "students": "fas fa-user-friends", # App icon for "Estudiantes"
        "core.PreEnrollmentProfile": "fas fa-id-card",
        "core.StudentEnrollment": "fas fa-user-graduate",
        "students.StudentSubmission": "fas fa-file-upload", # Model in students app

        # Iconos para modelos en Gestión de Personal
        "core.CoordinatorAssignment": "fas fa-sitemap",

        # Iconos para Comunicación
        "core.ChatRoom": "fas fa-comments",
        "core.ChatMessage": "fas fa-comment-dots",

        # Iconos para la app teachers si se usa
        "teachers": "fas fa-chalkboard-teacher", # Icono genérico para la app 'teachers'
        # "teachers.TeacherAssignment": "fas fa-address-book", # Ejemplo si existiera este modelo en la app teachers
        # "teachers.Activity": "fas fa-pencil-ruler",
        # "teachers.Grade": "fas fa-marker",

        # Modelos ocultos (aunque se muevan, si estaban ocultos y deben seguir así, mantenerlos)
        "core.ReportCardEntry": "fas fa-list-ol", # Icono por si se muestra en otro lado
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": "css/admin_customizations.css",
    "custom_js": None,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,

    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    "language_chooser": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True, # Para hacer el cuerpo del texto un poco más pequeño
    "brand_small_text": False,
    "brand_colour": "navbar-primary", # Color primario para la marca
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light", # Barra de navegación clara
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary", # Barra lateral oscura con acento primario
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False, # Estilo plano para la navegación lateral
    "theme": "default", # Tema por defecto, se puede cambiar a otros como "cerulean", "cosmo", "flatly", "journal", "litera", "lumen", "lux", "materia", "minty", "pulse", "sandstone", "simplex", "sketchy", "slate", "solar", "spacelab", "superhero", "united", "yeti"
    "dark_mode_theme": None, # Se puede poner un tema específico para modo oscuro
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True # Hacer que la barra de acciones sea pegajosa
}
